% ÒÆ³ýº¯ÊýÂ·¾¶

rmpath('acquisition')
rmpath('ambiguity')
rmpath('analysis')
rmpath('app')
rmpath('BD910')
rmpath('display')
rmpath('parsing')
rmpath('position')
rmpath('shortcut')
rmpath('temp')
rmpath('test')
rmpath('tracking')
rmpath('utility')